import "./load-env"
import { clerk, setupClerkTestingToken } from "@clerk/testing/playwright"
import { expect, test } from "@playwright/test"

test("an anonymous visitor can browse and open a recipe", async ({ page }) => {
  if (process.env.CLERK_SECRET_KEY) await setupClerkTestingToken({ page })
  await page.goto("/recipes")
  await expect(page.getByRole("heading", { name: "¿Qué preparamos hoy?" })).toBeVisible()
  const recipe = page.getByRole("link", { name: /V60 Regular/ })
  await expect(recipe).toBeVisible()
  await recipe.click()
  await expect(page).toHaveURL(/\/recipes$/)
  await expect(page.getByRole("dialog").getByRole("heading", { name: "V60 Regular" })).toBeVisible()
  await page.getByRole("button", { name: "Cerrar receta" }).click()
  await expect(page).toHaveURL(/\/recipes$/)
})

test("search filters are represented in the URL", async ({ page }) => {
  if (process.env.CLERK_SECRET_KEY) await setupClerkTestingToken({ page })
  await page.goto("/recipes")
  await page.getByRole("button", { name: "Filtros" }).click()
  await page.getByRole("button", { name: "V60" }).click()
  await expect(page).toHaveURL(/\/recipes$/)
  await page.getByRole("button", { name: "Ver resultados" }).click()
  await expect(page).toHaveURL(/method=v60/)
  await expect(page.getByRole("link", { name: /V60 Regular/ })).toBeVisible()
})

test("the recipe timer starts without changing the recipe layout or route", async ({ page }) => {
  if (process.env.CLERK_SECRET_KEY) await setupClerkTestingToken({ page })
  await page.goto("/recipes")
  await page.getByRole("link", { name: /V60 Regular/ }).click()
  const dialog = page.getByRole("dialog")
  await dialog.getByRole("button", { name: "Más acciones" }).click()
  await expect(dialog.getByRole("menu", { name: "Acciones de receta" })).toBeVisible()
  await dialog.getByRole("button", { name: "Más acciones" }).click()
  await page.getByRole("button", { name: "Iniciar", exact: true }).click()
  await expect(page).toHaveURL(/\/recipes$/)
  await expect(dialog.getByRole("heading", { name: "V60 Regular" })).toBeVisible()
  await expect(dialog.getByRole("button", { name: "Cerrar receta" })).toBeVisible()
  await expect(dialog.getByRole("button", { name: "Más acciones" })).toBeVisible()
  await expect(page.getByRole("button", { name: "Pausar" })).toBeVisible()
  await page.getByRole("button", { name: "Pausar" }).click()
  await expect(page.getByRole("button", { name: "Iniciar", exact: true })).toBeVisible()
  await dialog.getByRole("button", { name: "Cerrar receta" }).click()
  await expect(dialog).not.toBeVisible()
})

test("an authenticated user can persist a saved recipe", async ({ page }) => {
  test.skip(!process.env.CLERK_E2E_USER_EMAIL, "CLERK_E2E_USER_EMAIL is not configured")
  await setupClerkTestingToken({ page })
  await page.goto("/recipes")
  await clerk.signIn({ page, emailAddress: process.env.CLERK_E2E_USER_EMAIL! })
  await page.reload()
  await page.getByRole("link", { name: /V60 Regular/ }).click()
  const dialog = page.getByRole("dialog")
  await dialog.getByRole("button", { name: "Más acciones" }).click()
  await dialog.getByRole("menuitemcheckbox", { name: "Guardar", exact: true }).click()
  await expect(dialog.getByRole("menu", { name: "Acciones de receta" })).toBeVisible()
  await page.goto("/saved")
  await expect(page.getByRole("link", { name: /V60 Regular/ })).toBeVisible()
})

test("an authenticated user can create a personal recipe API key", async ({ page }) => {
  test.skip(!process.env.CLERK_E2E_USER_EMAIL, "CLERK_E2E_USER_EMAIL is not configured")
  await setupClerkTestingToken({ page })
  await page.goto("/profile")
  await clerk.signIn({ page, emailAddress: process.env.CLERK_E2E_USER_EMAIL! })
  await page.goto("/profile")

  await page.getByRole("button", { name: /API key.*Crear recetas desde la API/ }).click()
  const dialog = page.getByRole("dialog", { name: "API key para recetas" })
  await expect(dialog).toBeVisible()
  await dialog.getByRole("button", { name: "Crear API key" }).click()
  await expect(dialog.getByLabel("Nueva API key")).toHaveValue(/^koda_sk_[A-Za-z0-9_-]{43}$/)
  await expect(dialog.getByText("Koda no volverá a mostrar esta clave")).toBeVisible()
})
