import type { RecipeInput } from "@/lib/domain"

export type SeedRecipe = RecipeInput & { legacy_id: string }

export const SEED_RECIPES: SeedRecipe[] = [
  {
    legacy_id: "r1",
    name: "V60 clásico balanceado",
    author: "Ana Torres",
    method: "v60",
    image: "/methods/v60.png",
    coffee_g: 18,
    water_ml: 300,
    temperature_c: 93,
    grind: { target: "v60" },
    preparation: [
      "Enjuaga el filtro con agua caliente y desecha el agua.",
      "Añade el café molido y crea un pequeño cráter en el centro.",
      "Realiza el bloom con 50 ml y espera 30 segundos.",
      "Vierte en espiral hasta alcanzar los 300 ml.",
      "Deja drenar por completo antes de servir.",
    ],
    steps: [
      { instruction: "Bloom — vierte 50 ml", start: 0, end: 30 },
      { instruction: "Primer vertido — hasta 150 ml", start: 30, end: 75 },
      { instruction: "Segundo vertido — hasta 300 ml", start: 75, end: 120 },
      { instruction: "Drenado final", start: 120, end: 165 },
    ],
  },
  {
    legacy_id: "r2",
    name: "AeroPress invertido intenso",
    author: "Luis Gómez",
    method: "aeropress",
    image: "/methods/aeropress.png",
    coffee_g: 16,
    water_ml: 220,
    temperature_c: 85,
    grind: { target: "aeropress" },
    preparation: [
      "Monta la AeroPress en posición invertida.",
      "Añade el café y todo el agua.",
      "Revuelve 10 segundos y coloca la tapa con filtro.",
      "Voltea sobre la taza y presiona lentamente.",
    ],
    steps: [
      { instruction: "Vierte 220 ml y revuelve", start: 0, end: 20 },
      { instruction: "Reposo", start: 20, end: 80 },
      { instruction: "Voltea y presiona", start: 80, end: 110 },
    ],
  },
  {
    legacy_id: "r3",
    name: "Chemex para dos",
    author: "María Ruiz",
    method: "chemex",
    image: "/methods/chemex.png",
    coffee_g: 30,
    water_ml: 500,
    temperature_c: 94,
    grind: { target: "chemex" },
    preparation: [
      "Coloca el filtro con la triple capa hacia el pico.",
      "Enjuaga y desecha el agua.",
      "Bloom con 60 ml durante 40 segundos.",
      "Vierte en etapas hasta 500 ml.",
    ],
    steps: [
      { instruction: "Bloom — 60 ml", start: 0, end: 40 },
      { instruction: "Vertido hasta 250 ml", start: 40, end: 100 },
      { instruction: "Vertido hasta 500 ml", start: 100, end: 160 },
      { instruction: "Drenado", start: 160, end: 240 },
    ],
  },
  {
    legacy_id: "r4",
    name: "Prensa francesa suave",
    author: "Carlos Díaz",
    method: "french-press",
    image: "/methods/french-press.png",
    coffee_g: 30,
    water_ml: 450,
    temperature_c: 92,
    grind: { target: "frenchpress" },
    preparation: [
      "Añade el café molido grueso.",
      "Vierte toda el agua y revuelve la costra a los 4 min.",
      "Espera hasta los 8 minutos.",
      "Presiona el émbolo lentamente y sirve.",
    ],
    steps: [
      { instruction: "Vierte 450 ml", start: 0, end: 30 },
      { instruction: "Reposo", start: 30, end: 240 },
      { instruction: "Rompe la costra y revuelve", start: 240, end: 270 },
      { instruction: "Reposo final y presiona", start: 270, end: 480 },
    ],
  },
  {
    legacy_id: "r5",
    name: "Moka mañanera",
    author: "Sofía Peña",
    method: "moka",
    image: "/methods/moka.png",
    coffee_g: 20,
    water_ml: 150,
    temperature_c: 96,
    grind: { target: "moka" },
    preparation: [
      "Llena la base con agua caliente hasta la válvula.",
      "Coloca el café sin compactar.",
      "Cierra y pon a fuego medio.",
      "Retira cuando salga el gorgoteo.",
    ],
    steps: [
      { instruction: "Calentamiento", start: 0, end: 120 },
      { instruction: "Extracción", start: 120, end: 180 },
    ],
  },
  {
    legacy_id: "r6",
    name: "V60 Regular",
    author: "Benji Rodriguez",
    method: "v60",
    image: "/methods/v60-benji.png",
    coffee_g: 15,
    water_ml: 200,
    temperature_c: 80,
    grind: { target: "v60" },
    preparation: [
      "Pesa 15 g de café.",
      "Ajusta el Baratza Encore ESP a 28 clicks.",
      "Calienta 200 ml de agua a 80 °C.",
    ],
    steps: [
      { instruction: "Vierte 50 ml de agua para el blooming.", start: 0, end: 10 },
      { instruction: "Espera hasta los 30 segundos.", start: 10, end: 30 },
      { instruction: "Vierte 150 ml de agua hasta alcanzar 200 ml totales.", start: 30, end: 40 },
      { instruction: "Deja drenar completamente.", start: 40, end: 150 },
    ],
  },
]
